FROM 711048114373.dkr.ecr.us-east-1.amazonaws.com/canary-scanner-base:latest

COPY canary/src canary/src
COPY canary/templates canary/templates

# Install Canary's dependencies  
RUN pip install -r requirements.txt
RUN mkdir canary/output
RUN mkdir canary/output/payloads
RUN mkdir canary/output/pages
RUN mkdir canary/output/forms
RUN mkdir canary/output/scripts
RUN mkdir canary/output/unknown_cookies
RUN mkdir canary/output/error_sites

# Setting scan.py as the default command
CMD python3 scan.py --scan --analyse --pages --forms --scripts --all_cookies --allow_ot_cookies --page_limit 0 --num_browsers 5
